# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: /home/circleci/website
    docker:
      - image: circleci/node:8.9.0
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: generate-tmp
          command: |
            npm run clean
            npm run generate:template
            npm run generate:css
            npm run move:assets
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - website


